### PR TITLE
Handle end event for readable stream in readFile

### PR DESCRIPTION
**Pull request by tushar-rishav**

### CODE REVIEW

**Review by zxpan — COMMENTED** [review]
This change is good, but perhaps not enough I guess.

The change I made is the following
In createReadStream(), add the following: this is the latest code from https://github.com/harrisiirak/webhdfs/blob/master/lib/webhdfs.js

req.on('complete', function (err) {
    req.emit('end');
 });


Also see abclipper-ui2 : /mnt/alpha/production/srcs/master-latest-git/3p/pkgs-linux/node/lib/node_modules/webhdfs/lib/webhdfs.js

**Comment by tushar-rishav** [comment]
@zxpan Couple of points:
* On adding `complete` event listener in `createReadStream`, we need to avoid emitting end for retying case otherwise the ahdfs client would move on with the function call and wouldn't wait for the underlying retry mechanism to conclude. That's the reason, I removed it from `createReadStream`.
[Besides, the `complete` even is nested under `end`, so should be anyway okay I think to drop it or replace it with `end` alone elsewhere](https://github.com/request/request/blob/master/request.js#L1098)
* Also, since there is no `complete` event in nodejs readable stream module and it seems to be used only as an internal notification in `request` module [to implement callback based options](https://github.com/request/request/blob/master/request.js#L188), I think by design, `complete` event wasn't meant to be used outside rather `end` is to be used.

Please let me know your thoughts on the above or I misunderstood the design above.

Also, regarding the present change in abclipper-ui2 machine, the changes seems very similar to the latest forked webhdfs except the addition of a new `webhdfsStream` stream which is being used to pipe ( sort of as proxy stream? ) the data from retryStream -> original request stream. I'm curious about the approach of this design or anything I'm missing here?

**Comment by zxpan** [comment]
Tushar, with your concern, I did not pay much attention to it.  let stick your approach now.
W.r.t new webhdfsStream stream, my view is that this approach is cleaner. 
Anyhow we should write unit tests to cover all possible cases so we can go from there.

**Comment by tushar-rishav** [comment]
I agree, we need to write unit tests.
Going with the merge for now.

**Pull request merged**
